/**
 * Curated catalog of ~150 KiCad standard library symbols grouped by category.
 * Used by the SymbolBrowser component to let users pick and place symbols.
 */

export interface CatalogEntry {
  libId: string;
  name: string;
  description: string;
  keywords: string[];
  category: string;
  pinCount: number;
  defaultValue: string;
  designatorPrefix: string;
}

export const SYMBOL_CATALOG: CatalogEntry[] = [
  // ── Passives ──────────────────────────────────────────────────────────────
  {
    libId: 'Device:R',
    name: 'R',
    description: 'Resistor',
    keywords: ['resistor', 'res', 'ohm', 'pull-up', 'pull-down'],
    category: 'Passives',
    pinCount: 2,
    defaultValue: '10k',
    designatorPrefix: 'R',
  },
  {
    libId: 'Device:R_Small',
    name: 'R_Small',
    description: 'Resistor (small symbol)',
    keywords: ['resistor', 'res', 'small'],
    category: 'Passives',
    pinCount: 2,
    defaultValue: '10k',
    designatorPrefix: 'R',
  },
  {
    libId: 'Device:R_Pack04',
    name: 'R_Pack04',
    description: 'Resistor network 4-pack',
    keywords: ['resistor', 'network', 'pack', 'array'],
    category: 'Passives',
    pinCount: 8,
    defaultValue: '10k',
    designatorPrefix: 'RN',
  },
  {
    libId: 'Device:R_Variable',
    name: 'R_Variable',
    description: 'Variable resistor / potentiometer',
    keywords: ['pot', 'potentiometer', 'trim', 'variable', 'rheostat'],
    category: 'Passives',
    pinCount: 3,
    defaultValue: '10k',
    designatorPrefix: 'RV',
  },
  {
    libId: 'Device:C',
    name: 'C',
    description: 'Capacitor (non-polarised)',
    keywords: ['capacitor', 'cap', 'bypass', 'decoupling', 'ceramic'],
    category: 'Passives',
    pinCount: 2,
    defaultValue: '100n',
    designatorPrefix: 'C',
  },
  {
    libId: 'Device:C_Polarized',
    name: 'C_Polarized',
    description: 'Capacitor (polarised / electrolytic)',
    keywords: ['capacitor', 'electrolytic', 'polarised', 'bulk'],
    category: 'Passives',
    pinCount: 2,
    defaultValue: '100u',
    designatorPrefix: 'C',
  },
  {
    libId: 'Device:C_Small',
    name: 'C_Small',
    description: 'Capacitor (small symbol)',
    keywords: ['capacitor', 'small'],
    category: 'Passives',
    pinCount: 2,
    defaultValue: '100n',
    designatorPrefix: 'C',
  },
  {
    libId: 'Device:L',
    name: 'L',
    description: 'Inductor',
    keywords: ['inductor', 'coil', 'choke', 'ferrite'],
    category: 'Passives',
    pinCount: 2,
    defaultValue: '10u',
    designatorPrefix: 'L',
  },
  {
    libId: 'Device:L_Small',
    name: 'L_Small',
    description: 'Inductor (small symbol)',
    keywords: ['inductor', 'coil', 'small'],
    category: 'Passives',
    pinCount: 2,
    defaultValue: '10u',
    designatorPrefix: 'L',
  },
  {
    libId: 'Device:L_Core_Iron',
    name: 'L_Core_Iron',
    description: 'Inductor with iron core',
    keywords: ['inductor', 'iron', 'core', 'power'],
    category: 'Passives',
    pinCount: 2,
    defaultValue: '100u',
    designatorPrefix: 'L',
  },
  {
    libId: 'Device:Fuse',
    name: 'Fuse',
    description: 'Fuse',
    keywords: ['fuse', 'overcurrent', 'protection'],
    category: 'Passives',
    pinCount: 2,
    defaultValue: '1A',
    designatorPrefix: 'F',
  },
  {
    libId: 'Device:Polyfuse',
    name: 'Polyfuse',
    description: 'Resettable fuse / polyfuse',
    keywords: ['polyfuse', 'resettable', 'ptc', 'fuse'],
    category: 'Passives',
    pinCount: 2,
    defaultValue: '500mA',
    designatorPrefix: 'F',
  },
  {
    libId: 'Device:Crystal',
    name: 'Crystal',
    description: 'Quartz crystal resonator',
    keywords: ['crystal', 'xtal', 'oscillator', 'resonator', 'quartz'],
    category: 'Passives',
    pinCount: 2,
    defaultValue: '16MHz',
    designatorPrefix: 'Y',
  },
  {
    libId: 'Device:Resonator',
    name: 'Resonator',
    description: 'Ceramic resonator (3-pin)',
    keywords: ['resonator', 'ceramic', 'oscillator'],
    category: 'Passives',
    pinCount: 3,
    defaultValue: '16MHz',
    designatorPrefix: 'Y',
  },
  {
    libId: 'Device:Transformer',
    name: 'Transformer',
    description: 'Transformer (2 winding)',
    keywords: ['transformer', 'isolation', 'coupling', 'flyback'],
    category: 'Passives',
    pinCount: 4,
    defaultValue: 'T1',
    designatorPrefix: 'T',
  },
  {
    libId: 'Device:Battery_Cell',
    name: 'Battery_Cell',
    description: 'Single battery cell',
    keywords: ['battery', 'cell', 'power', 'coin', 'li-ion'],
    category: 'Passives',
    pinCount: 2,
    defaultValue: '3.7V',
    designatorPrefix: 'BT',
  },

  // ── Semiconductors ────────────────────────────────────────────────────────
  {
    libId: 'Device:D',
    name: 'D',
    description: 'Diode (general purpose)',
    keywords: ['diode', 'rectifier', '1n4148', '1n4001', '1n4007'],
    category: 'Semiconductors',
    pinCount: 2,
    defaultValue: '1N4148',
    designatorPrefix: 'D',
  },
  {
    libId: 'Device:D_Schottky',
    name: 'D_Schottky',
    description: 'Schottky diode',
    keywords: ['schottky', 'diode', 'ss14', 'bat43', 'low drop'],
    category: 'Semiconductors',
    pinCount: 2,
    defaultValue: 'SS14',
    designatorPrefix: 'D',
  },
  {
    libId: 'Device:D_Zener',
    name: 'D_Zener',
    description: 'Zener diode',
    keywords: ['zener', 'regulation', 'voltage clamp', 'tvs'],
    category: 'Semiconductors',
    pinCount: 2,
    defaultValue: '5V1',
    designatorPrefix: 'D',
  },
  {
    libId: 'Device:D_TVS',
    name: 'D_TVS',
    description: 'Transient-voltage-suppression diode',
    keywords: ['tvs', 'esd', 'protection', 'transient'],
    category: 'Semiconductors',
    pinCount: 2,
    defaultValue: '12V',
    designatorPrefix: 'D',
  },
  {
    libId: 'Device:LED',
    name: 'LED',
    description: 'Light-emitting diode',
    keywords: ['led', 'light', 'indicator', 'optical'],
    category: 'Semiconductors',
    pinCount: 2,
    defaultValue: 'LED',
    designatorPrefix: 'D',
  },
  {
    libId: 'Device:LED_RGB',
    name: 'LED_RGB',
    description: 'RGB LED (4-pin common cathode)',
    keywords: ['led', 'rgb', 'colour', 'ws2812'],
    category: 'Semiconductors',
    pinCount: 4,
    defaultValue: 'LED_RGB',
    designatorPrefix: 'D',
  },
  {
    libId: 'Device:Q_NPN_BCE',
    name: 'Q_NPN_BCE',
    description: 'NPN BJT (Base-Collector-Emitter)',
    keywords: ['npn', 'bjt', 'transistor', '2n3904', 'bc547'],
    category: 'Semiconductors',
    pinCount: 3,
    defaultValue: '2N3904',
    designatorPrefix: 'Q',
  },
  {
    libId: 'Device:Q_PNP_BCE',
    name: 'Q_PNP_BCE',
    description: 'PNP BJT (Base-Collector-Emitter)',
    keywords: ['pnp', 'bjt', 'transistor', '2n3906', 'bc557'],
    category: 'Semiconductors',
    pinCount: 3,
    defaultValue: '2N3906',
    designatorPrefix: 'Q',
  },
  {
    libId: 'Device:Q_NMOS_GSD',
    name: 'Q_NMOS_GSD',
    description: 'N-channel MOSFET (Gate-Source-Drain)',
    keywords: ['nmos', 'nfet', 'mosfet', 'n-channel', '2n7002', 'irf540'],
    category: 'Semiconductors',
    pinCount: 3,
    defaultValue: '2N7002',
    designatorPrefix: 'Q',
  },
  {
    libId: 'Device:Q_PMOS_GSD',
    name: 'Q_PMOS_GSD',
    description: 'P-channel MOSFET (Gate-Source-Drain)',
    keywords: ['pmos', 'pfet', 'mosfet', 'p-channel', 'bs250', 'irf9540'],
    category: 'Semiconductors',
    pinCount: 3,
    defaultValue: 'BS250',
    designatorPrefix: 'Q',
  },

  // ── Amplifiers ────────────────────────────────────────────────────────────
  {
    libId: 'Amplifier_Operational:LM358',
    name: 'LM358',
    description: 'Dual op-amp, low-power',
    keywords: ['op-amp', 'opamp', 'amplifier', 'lm358', 'dual'],
    category: 'Amplifiers',
    pinCount: 8,
    defaultValue: 'LM358',
    designatorPrefix: 'U',
  },
  {
    libId: 'Amplifier_Operational:LM741',
    name: 'LM741',
    description: 'General-purpose op-amp',
    keywords: ['op-amp', 'opamp', 'amplifier', 'lm741'],
    category: 'Amplifiers',
    pinCount: 8,
    defaultValue: 'LM741',
    designatorPrefix: 'U',
  },
  {
    libId: 'Amplifier_Operational:TL071',
    name: 'TL071',
    description: 'Low-noise JFET input op-amp',
    keywords: ['op-amp', 'opamp', 'amplifier', 'tl071', 'tl072', 'jfet', 'low noise'],
    category: 'Amplifiers',
    pinCount: 8,
    defaultValue: 'TL071',
    designatorPrefix: 'U',
  },
  {
    libId: 'Amplifier_Operational:LM324',
    name: 'LM324',
    description: 'Quad op-amp',
    keywords: ['op-amp', 'opamp', 'amplifier', 'lm324', 'quad'],
    category: 'Amplifiers',
    pinCount: 14,
    defaultValue: 'LM324',
    designatorPrefix: 'U',
  },
  {
    libId: 'Amplifier_Instrumentation:INA128',
    name: 'INA128',
    description: 'Precision instrumentation amplifier',
    keywords: ['instrumentation', 'ina', 'amplifier', 'differential', 'precision'],
    category: 'Amplifiers',
    pinCount: 8,
    defaultValue: 'INA128',
    designatorPrefix: 'U',
  },
  {
    libId: 'Amplifier_Operational:MCP6001',
    name: 'MCP6001',
    description: 'Rail-to-rail op-amp (Microchip)',
    keywords: ['op-amp', 'opamp', 'rail-to-rail', 'mcp6001'],
    category: 'Amplifiers',
    pinCount: 5,
    defaultValue: 'MCP6001',
    designatorPrefix: 'U',
  },
  {
    libId: 'Amplifier_Operational:OPA2134',
    name: 'OPA2134',
    description: 'High-performance audio op-amp',
    keywords: ['op-amp', 'audio', 'opa', 'hi-fi', 'precision'],
    category: 'Amplifiers',
    pinCount: 8,
    defaultValue: 'OPA2134',
    designatorPrefix: 'U',
  },

  // ── Comparators ───────────────────────────────────────────────────────────
  {
    libId: 'Comparator:LM393',
    name: 'LM393',
    description: 'Dual voltage comparator',
    keywords: ['comparator', 'lm393', 'dual'],
    category: 'Comparators',
    pinCount: 8,
    defaultValue: 'LM393',
    designatorPrefix: 'U',
  },
  {
    libId: 'Comparator:LM311',
    name: 'LM311',
    description: 'Voltage comparator',
    keywords: ['comparator', 'lm311'],
    category: 'Comparators',
    pinCount: 8,
    defaultValue: 'LM311',
    designatorPrefix: 'U',
  },
  {
    libId: 'Comparator:LM339',
    name: 'LM339',
    description: 'Quad low-power comparator',
    keywords: ['comparator', 'lm339', 'quad'],
    category: 'Comparators',
    pinCount: 14,
    defaultValue: 'LM339',
    designatorPrefix: 'U',
  },

  // ── Regulators ────────────────────────────────────────────────────────────
  {
    libId: 'Regulator_Linear:L7805',
    name: 'L7805',
    description: '+5V 1A linear regulator (78xx series)',
    keywords: ['regulator', 'ldo', '7805', '5v', 'linear'],
    category: 'Regulators',
    pinCount: 3,
    defaultValue: 'L7805',
    designatorPrefix: 'U',
  },
  {
    libId: 'Regulator_Linear:L7812',
    name: 'L7812',
    description: '+12V 1A linear regulator (78xx series)',
    keywords: ['regulator', 'ldo', '7812', '12v', 'linear'],
    category: 'Regulators',
    pinCount: 3,
    defaultValue: 'L7812',
    designatorPrefix: 'U',
  },
  {
    libId: 'Regulator_Linear:LM317_TO-220',
    name: 'LM317',
    description: 'Adjustable positive linear regulator',
    keywords: ['regulator', 'adjustable', 'lm317', 'linear'],
    category: 'Regulators',
    pinCount: 3,
    defaultValue: 'LM317',
    designatorPrefix: 'U',
  },
  {
    libId: 'Regulator_Linear:AMS1117-3.3',
    name: 'AMS1117-3.3',
    description: '3.3V 1A LDO regulator',
    keywords: ['ldo', 'regulator', 'ams1117', '3.3v'],
    category: 'Regulators',
    pinCount: 3,
    defaultValue: 'AMS1117-3.3',
    designatorPrefix: 'U',
  },
  {
    libId: 'Regulator_Linear:AMS1117-5.0',
    name: 'AMS1117-5.0',
    description: '5V 1A LDO regulator',
    keywords: ['ldo', 'regulator', 'ams1117', '5v'],
    category: 'Regulators',
    pinCount: 3,
    defaultValue: 'AMS1117-5.0',
    designatorPrefix: 'U',
  },
  {
    libId: 'Regulator_Linear:MCP1700-3302E',
    name: 'MCP1700-3.3',
    description: '3.3V 250mA ultra-low quiescent LDO',
    keywords: ['ldo', 'regulator', 'mcp1700', 'low iq'],
    category: 'Regulators',
    pinCount: 3,
    defaultValue: 'MCP1700-3302E',
    designatorPrefix: 'U',
  },
  {
    libId: 'Regulator_Switching:LM2596-5.0',
    name: 'LM2596-5.0',
    description: '5V 3A step-down switching regulator',
    keywords: ['buck', 'switching', 'lm2596', 'dc-dc', 'step-down'],
    category: 'Regulators',
    pinCount: 5,
    defaultValue: 'LM2596-5.0',
    designatorPrefix: 'U',
  },
  {
    libId: 'Regulator_Switching:LM2596ADJ',
    name: 'LM2596ADJ',
    description: 'Adjustable 3A step-down switching regulator',
    keywords: ['buck', 'switching', 'lm2596', 'adjustable', 'dc-dc'],
    category: 'Regulators',
    pinCount: 5,
    defaultValue: 'LM2596ADJ',
    designatorPrefix: 'U',
  },
  {
    libId: 'Regulator_Switching:TPS63020',
    name: 'TPS63020',
    description: 'High-efficiency buck-boost converter',
    keywords: ['buck-boost', 'switching', 'tps63020', 'dc-dc'],
    category: 'Regulators',
    pinCount: 16,
    defaultValue: 'TPS63020',
    designatorPrefix: 'U',
  },

  // ── Logic ─────────────────────────────────────────────────────────────────
  {
    libId: 'Logic_Gate:74HC00',
    name: '74HC00',
    description: 'Quad 2-input NAND gate (74HC)',
    keywords: ['nand', 'logic', '74hc00', 'gate', 'quad'],
    category: 'Logic',
    pinCount: 14,
    defaultValue: '74HC00',
    designatorPrefix: 'U',
  },
  {
    libId: 'Logic_Gate:74HC04',
    name: '74HC04',
    description: 'Hex inverter (74HC)',
    keywords: ['inverter', 'not', 'hex', '74hc04', 'logic', 'buffer'],
    category: 'Logic',
    pinCount: 14,
    defaultValue: '74HC04',
    designatorPrefix: 'U',
  },
  {
    libId: 'Logic_Gate:74HC08',
    name: '74HC08',
    description: 'Quad 2-input AND gate (74HC)',
    keywords: ['and', 'logic', '74hc08', 'gate', 'quad'],
    category: 'Logic',
    pinCount: 14,
    defaultValue: '74HC08',
    designatorPrefix: 'U',
  },
  {
    libId: 'Logic_Gate:74HC32',
    name: '74HC32',
    description: 'Quad 2-input OR gate (74HC)',
    keywords: ['or', 'logic', '74hc32', 'gate', 'quad'],
    category: 'Logic',
    pinCount: 14,
    defaultValue: '74HC32',
    designatorPrefix: 'U',
  },
  {
    libId: 'Logic_Gate:74HC14',
    name: '74HC14',
    description: 'Hex Schmitt-trigger inverter (74HC)',
    keywords: ['schmitt', 'inverter', '74hc14', 'logic', 'debounce'],
    category: 'Logic',
    pinCount: 14,
    defaultValue: '74HC14',
    designatorPrefix: 'U',
  },
  {
    libId: 'Logic_FF:74HC74',
    name: '74HC74',
    description: 'Dual D-type flip-flop (74HC)',
    keywords: ['flip-flop', 'd-ff', '74hc74', 'logic', 'register'],
    category: 'Logic',
    pinCount: 14,
    defaultValue: '74HC74',
    designatorPrefix: 'U',
  },
  {
    libId: 'Logic_Gate:74LS00',
    name: '74LS00',
    description: 'Quad 2-input NAND gate (74LS)',
    keywords: ['nand', 'logic', '74ls00', 'gate', 'ls-ttl'],
    category: 'Logic',
    pinCount: 14,
    defaultValue: '74LS00',
    designatorPrefix: 'U',
  },
  {
    libId: 'Logic_Gate:SN74AHCT1G00',
    name: 'SN74AHCT1G00',
    description: 'Single 2-input NAND gate (AHC)',
    keywords: ['nand', 'logic', 'sn74ahct1g00', 'single gate', 'sot-23'],
    category: 'Logic',
    pinCount: 5,
    defaultValue: 'SN74AHCT1G00',
    designatorPrefix: 'U',
  },
  {
    libId: 'Logic_ShiftRegister:74HC595',
    name: '74HC595',
    description: '8-bit serial-in parallel-out shift register',
    keywords: ['shift register', '74hc595', 'sipo', 'serial', 'io expander'],
    category: 'Logic',
    pinCount: 16,
    defaultValue: '74HC595',
    designatorPrefix: 'U',
  },
  {
    libId: 'Logic_ShiftRegister:74HC165',
    name: '74HC165',
    description: '8-bit parallel-in serial-out shift register',
    keywords: ['shift register', '74hc165', 'piso', 'serial', 'input'],
    category: 'Logic',
    pinCount: 16,
    defaultValue: '74HC165',
    designatorPrefix: 'U',
  },

  // ── MCU / SoC ─────────────────────────────────────────────────────────────
  {
    libId: 'MCU_Microchip_ATmega:ATmega328P-PU',
    name: 'ATmega328P',
    description: 'Microchip ATmega328P 8-bit MCU (Arduino)',
    keywords: ['arduino', 'atmega', 'avr', 'microcontroller', 'atmega328p'],
    category: 'MCU',
    pinCount: 28,
    defaultValue: 'ATmega328P',
    designatorPrefix: 'U',
  },
  {
    libId: 'MCU_ST_STM32F1:STM32F103C8Tx',
    name: 'STM32F103C8Tx',
    description: 'ST Micro 32-bit ARM Cortex-M3 MCU (Blue Pill)',
    keywords: ['stm32', 'arm', 'cortex', 'microcontroller', 'blue pill', 'st'],
    category: 'MCU',
    pinCount: 48,
    defaultValue: 'STM32F103C8T6',
    designatorPrefix: 'U',
  },
  {
    libId: 'RF_Module:ESP32-WROOM-32',
    name: 'ESP32-WROOM-32',
    description: 'Espressif ESP32 Wi-Fi/BT module',
    keywords: ['esp32', 'wifi', 'bluetooth', 'iot', 'espressif'],
    category: 'MCU',
    pinCount: 38,
    defaultValue: 'ESP32-WROOM-32',
    designatorPrefix: 'U',
  },
  {
    libId: 'MCU_RaspberryPi:RP2040',
    name: 'RP2040',
    description: 'Raspberry Pi RP2040 dual Cortex-M0+ MCU',
    keywords: ['rp2040', 'raspberry pi', 'arm', 'cortex', 'microcontroller'],
    category: 'MCU',
    pinCount: 56,
    defaultValue: 'RP2040',
    designatorPrefix: 'U',
  },
  {
    libId: 'MCU_Microchip_PIC16:PIC16F877A-IP',
    name: 'PIC16F877A',
    description: 'Microchip PIC16F877A 8-bit MCU',
    keywords: ['pic', 'microchip', 'pic16f877a', '8-bit', 'microcontroller'],
    category: 'MCU',
    pinCount: 40,
    defaultValue: 'PIC16F877A',
    designatorPrefix: 'U',
  },
  {
    libId: 'MCU_Atmel_ATtiny:ATtiny85-20PU',
    name: 'ATtiny85',
    description: 'Microchip ATtiny85 8-bit AVR MCU',
    keywords: ['attiny', 'avr', 'tiny', 'microcontroller', 'small'],
    category: 'MCU',
    pinCount: 8,
    defaultValue: 'ATtiny85',
    designatorPrefix: 'U',
  },

  // ── Interface / Comms ─────────────────────────────────────────────────────
  {
    libId: 'Interface_UART:MAX232',
    name: 'MAX232',
    description: 'RS-232 line driver/receiver (+/-15V from 5V)',
    keywords: ['rs232', 'uart', 'max232', 'level shifter', 'serial'],
    category: 'Interface',
    pinCount: 16,
    defaultValue: 'MAX232',
    designatorPrefix: 'U',
  },
  {
    libId: 'Interface_RS485:MAX485',
    name: 'MAX485',
    description: 'RS-485 half-duplex transceiver',
    keywords: ['rs485', 'max485', 'differential', 'industrial', 'modbus'],
    category: 'Interface',
    pinCount: 8,
    defaultValue: 'MAX485',
    designatorPrefix: 'U',
  },
  {
    libId: 'Interface_USB:CH340G',
    name: 'CH340G',
    description: 'USB to UART bridge IC',
    keywords: ['usb', 'uart', 'ch340', 'ch340g', 'usb-serial'],
    category: 'Interface',
    pinCount: 16,
    defaultValue: 'CH340G',
    designatorPrefix: 'U',
  },
  {
    libId: 'Interface_USB:FT232RL',
    name: 'FT232RL',
    description: 'FTDI USB to UART/FIFO bridge',
    keywords: ['ftdi', 'usb', 'uart', 'ft232', 'usb-serial'],
    category: 'Interface',
    pinCount: 28,
    defaultValue: 'FT232RL',
    designatorPrefix: 'U',
  },
  {
    libId: 'Interface_I2C:NXP_PCA9505',
    name: 'PCA9505',
    description: 'I2C 40-bit I/O expander',
    keywords: ['i2c', 'io expander', 'pca', 'gpio'],
    category: 'Interface',
    pinCount: 28,
    defaultValue: 'PCA9505',
    designatorPrefix: 'U',
  },
  {
    libId: 'Interface_CAN:MCP2551',
    name: 'MCP2551',
    description: 'High-speed CAN bus transceiver',
    keywords: ['can', 'canbus', 'mcp2551', 'transceiver', 'obd'],
    category: 'Interface',
    pinCount: 8,
    defaultValue: 'MCP2551',
    designatorPrefix: 'U',
  },
  {
    libId: 'Interface_SPI:74HC595',
    name: 'SPI-DAC',
    description: 'SPI digital-to-analog converter (generic)',
    keywords: ['spi', 'dac', 'analog', 'serial'],
    category: 'Interface',
    pinCount: 8,
    defaultValue: 'MCP4901',
    designatorPrefix: 'U',
  },

  // ── Power symbols ─────────────────────────────────────────────────────────
  {
    libId: 'power:GND',
    name: 'GND',
    description: 'Ground power symbol',
    keywords: ['ground', 'gnd', 'power', 'reference'],
    category: 'Power',
    pinCount: 1,
    defaultValue: 'GND',
    designatorPrefix: '#PWR',
  },
  {
    libId: 'power:+3.3V',
    name: '+3.3V',
    description: '+3.3V power supply rail',
    keywords: ['3.3v', 'power', 'vcc', 'supply'],
    category: 'Power',
    pinCount: 1,
    defaultValue: '+3.3V',
    designatorPrefix: '#PWR',
  },
  {
    libId: 'power:+5V',
    name: '+5V',
    description: '+5V power supply rail',
    keywords: ['5v', 'power', 'vcc', 'supply', 'usb'],
    category: 'Power',
    pinCount: 1,
    defaultValue: '+5V',
    designatorPrefix: '#PWR',
  },
  {
    libId: 'power:+12V',
    name: '+12V',
    description: '+12V power supply rail',
    keywords: ['12v', 'power', 'supply'],
    category: 'Power',
    pinCount: 1,
    defaultValue: '+12V',
    designatorPrefix: '#PWR',
  },
  {
    libId: 'power:-12V',
    name: '-12V',
    description: '-12V power supply rail',
    keywords: ['-12v', 'power', 'negative', 'supply'],
    category: 'Power',
    pinCount: 1,
    defaultValue: '-12V',
    designatorPrefix: '#PWR',
  },
  {
    libId: 'power:VCC',
    name: 'VCC',
    description: 'VCC power supply rail',
    keywords: ['vcc', 'power', 'supply'],
    category: 'Power',
    pinCount: 1,
    defaultValue: 'VCC',
    designatorPrefix: '#PWR',
  },
  {
    libId: 'power:VDD',
    name: 'VDD',
    description: 'VDD power supply rail',
    keywords: ['vdd', 'power', 'supply'],
    category: 'Power',
    pinCount: 1,
    defaultValue: 'VDD',
    designatorPrefix: '#PWR',
  },
  {
    libId: 'power:VBUS',
    name: 'VBUS',
    description: 'USB VBUS power rail (+5V)',
    keywords: ['vbus', 'usb', 'power', '5v'],
    category: 'Power',
    pinCount: 1,
    defaultValue: 'VBUS',
    designatorPrefix: '#PWR',
  },
  {
    libId: 'power:VBAT',
    name: 'VBAT',
    description: 'Battery voltage rail',
    keywords: ['vbat', 'battery', 'power'],
    category: 'Power',
    pinCount: 1,
    defaultValue: 'VBAT',
    designatorPrefix: '#PWR',
  },
  {
    libId: 'power:AGND',
    name: 'AGND',
    description: 'Analog ground',
    keywords: ['agnd', 'ground', 'analog', 'power'],
    category: 'Power',
    pinCount: 1,
    defaultValue: 'AGND',
    designatorPrefix: '#PWR',
  },
  {
    libId: 'power:DGND',
    name: 'DGND',
    description: 'Digital ground',
    keywords: ['dgnd', 'ground', 'digital', 'power'],
    category: 'Power',
    pinCount: 1,
    defaultValue: 'DGND',
    designatorPrefix: '#PWR',
  },

  // ── Connectors ────────────────────────────────────────────────────────────
  {
    libId: 'Connector_Generic:Conn_01x02',
    name: 'Conn_01x02',
    description: '2-pin single-row connector',
    keywords: ['connector', '2-pin', 'header', 'jst'],
    category: 'Connectors',
    pinCount: 2,
    defaultValue: 'Conn_01x02',
    designatorPrefix: 'J',
  },
  {
    libId: 'Connector_Generic:Conn_01x03',
    name: 'Conn_01x03',
    description: '3-pin single-row connector',
    keywords: ['connector', '3-pin', 'header', 'jst'],
    category: 'Connectors',
    pinCount: 3,
    defaultValue: 'Conn_01x03',
    designatorPrefix: 'J',
  },
  {
    libId: 'Connector_Generic:Conn_01x04',
    name: 'Conn_01x04',
    description: '4-pin single-row connector',
    keywords: ['connector', '4-pin', 'header', 'i2c', 'jst'],
    category: 'Connectors',
    pinCount: 4,
    defaultValue: 'Conn_01x04',
    designatorPrefix: 'J',
  },
  {
    libId: 'Connector_Generic:Conn_01x08',
    name: 'Conn_01x08',
    description: '8-pin single-row connector',
    keywords: ['connector', '8-pin', 'header'],
    category: 'Connectors',
    pinCount: 8,
    defaultValue: 'Conn_01x08',
    designatorPrefix: 'J',
  },
  {
    libId: 'Connector_Generic:Conn_02x05',
    name: 'Conn_02x05',
    description: '2x5 dual-row connector (10-pin)',
    keywords: ['connector', '10-pin', 'jtag', 'isp', 'header'],
    category: 'Connectors',
    pinCount: 10,
    defaultValue: 'Conn_02x05',
    designatorPrefix: 'J',
  },
  {
    libId: 'Connector:USB_A',
    name: 'USB_A',
    description: 'USB Type-A receptacle',
    keywords: ['usb', 'usb-a', 'connector', 'host'],
    category: 'Connectors',
    pinCount: 4,
    defaultValue: 'USB_A',
    designatorPrefix: 'J',
  },
  {
    libId: 'Connector:USB_B',
    name: 'USB_B',
    description: 'USB Type-B receptacle',
    keywords: ['usb', 'usb-b', 'connector', 'device'],
    category: 'Connectors',
    pinCount: 4,
    defaultValue: 'USB_B',
    designatorPrefix: 'J',
  },
  {
    libId: 'Connector:USB_Micro_B',
    name: 'USB_Micro_B',
    description: 'USB Micro-B receptacle',
    keywords: ['usb', 'micro-b', 'micro usb', 'connector'],
    category: 'Connectors',
    pinCount: 5,
    defaultValue: 'USB_Micro_B',
    designatorPrefix: 'J',
  },
  {
    libId: 'Connector:USB_C_Receptacle_USB2.0',
    name: 'USB_C',
    description: 'USB Type-C receptacle (USB 2.0)',
    keywords: ['usb', 'usb-c', 'type-c', 'connector'],
    category: 'Connectors',
    pinCount: 24,
    defaultValue: 'USB_C',
    designatorPrefix: 'J',
  },
  {
    libId: 'Connector:RJ45',
    name: 'RJ45',
    description: 'RJ45 Ethernet connector (8P8C)',
    keywords: ['rj45', 'ethernet', 'lan', 'network', 'connector'],
    category: 'Connectors',
    pinCount: 8,
    defaultValue: 'RJ45',
    designatorPrefix: 'J',
  },
  {
    libId: 'Connector:Barrel_Jack',
    name: 'Barrel_Jack',
    description: 'DC barrel jack (power connector)',
    keywords: ['barrel', 'dc jack', 'power', 'connector'],
    category: 'Connectors',
    pinCount: 2,
    defaultValue: 'Barrel_Jack',
    designatorPrefix: 'J',
  },
  {
    libId: 'Connector:SMA',
    name: 'SMA',
    description: 'SMA RF coaxial connector',
    keywords: ['sma', 'rf', 'coax', 'antenna', 'connector'],
    category: 'Connectors',
    pinCount: 2,
    defaultValue: 'SMA',
    designatorPrefix: 'J',
  },

  // ── Switches ──────────────────────────────────────────────────────────────
  {
    libId: 'Device:SW_Push',
    name: 'SW_Push',
    description: 'Momentary push button switch',
    keywords: ['switch', 'button', 'push', 'tactile', 'momentary'],
    category: 'Switches',
    pinCount: 2,
    defaultValue: 'SW_Push',
    designatorPrefix: 'SW',
  },
  {
    libId: 'Device:SW_SPDT',
    name: 'SW_SPDT',
    description: 'SPDT toggle switch',
    keywords: ['switch', 'spdt', 'toggle', 'slide'],
    category: 'Switches',
    pinCount: 3,
    defaultValue: 'SW_SPDT',
    designatorPrefix: 'SW',
  },
  {
    libId: 'Device:SW_DIP_x02',
    name: 'SW_DIP_x2',
    description: 'DIP switch 2-position',
    keywords: ['dip', 'switch', 'configuration', 'jumper'],
    category: 'Switches',
    pinCount: 4,
    defaultValue: 'SW_DIP_x02',
    designatorPrefix: 'SW',
  },
  {
    libId: 'Device:SW_DPDT',
    name: 'SW_DPDT',
    description: 'DPDT switch',
    keywords: ['switch', 'dpdt', 'double pole'],
    category: 'Switches',
    pinCount: 6,
    defaultValue: 'SW_DPDT',
    designatorPrefix: 'SW',
  },
  {
    libId: 'Device:SW_Rotary_Encoder',
    name: 'SW_Rotary_Enc',
    description: 'Rotary encoder with push switch',
    keywords: ['encoder', 'rotary', 'switch', 'menu'],
    category: 'Switches',
    pinCount: 5,
    defaultValue: 'SW_Rotary_Enc',
    designatorPrefix: 'SW',
  },

  // ── Misc ──────────────────────────────────────────────────────────────────
  {
    libId: 'Device:Speaker',
    name: 'Speaker',
    description: 'Loudspeaker / transducer',
    keywords: ['speaker', 'audio', 'transducer', 'sound'],
    category: 'Misc',
    pinCount: 2,
    defaultValue: '8Ω',
    designatorPrefix: 'LS',
  },
  {
    libId: 'Device:Buzzer',
    name: 'Buzzer',
    description: 'Piezoelectric buzzer',
    keywords: ['buzzer', 'beeper', 'piezo', 'audio'],
    category: 'Misc',
    pinCount: 2,
    defaultValue: 'Buzzer',
    designatorPrefix: 'BZ',
  },
  {
    libId: 'Device:Relay_SPDT',
    name: 'Relay_SPDT',
    description: 'SPDT relay (coil + contacts)',
    keywords: ['relay', 'spdt', 'coil', 'mechanical', 'switch'],
    category: 'Misc',
    pinCount: 5,
    defaultValue: '5V',
    designatorPrefix: 'K',
  },
  {
    libId: 'Device:Motor_DC',
    name: 'Motor_DC',
    description: 'DC motor',
    keywords: ['motor', 'dc', 'actuator'],
    category: 'Misc',
    pinCount: 2,
    defaultValue: 'Motor_DC',
    designatorPrefix: 'M',
  },
  {
    libId: 'Device:Battery_Cell',
    name: 'Battery',
    description: 'Battery / cell',
    keywords: ['battery', 'cell', 'power'],
    category: 'Misc',
    pinCount: 2,
    defaultValue: 'BAT',
    designatorPrefix: 'BT',
  },
  {
    libId: 'Sensor:LM35',
    name: 'LM35',
    description: 'Precision Celsius temperature sensor',
    keywords: ['temperature', 'sensor', 'lm35', 'analog'],
    category: 'Misc',
    pinCount: 3,
    defaultValue: 'LM35',
    designatorPrefix: 'U',
  },
  {
    libId: 'Sensor:DHT22',
    name: 'DHT22',
    description: 'Humidity and temperature sensor',
    keywords: ['humidity', 'temperature', 'sensor', 'dht22', 'dht'],
    category: 'Misc',
    pinCount: 4,
    defaultValue: 'DHT22',
    designatorPrefix: 'U',
  },
  {
    libId: 'Sensor:HC-SR04',
    name: 'HC-SR04',
    description: 'Ultrasonic distance sensor',
    keywords: ['ultrasonic', 'sonar', 'distance', 'hc-sr04'],
    category: 'Misc',
    pinCount: 4,
    defaultValue: 'HC-SR04',
    designatorPrefix: 'U',
  },
  {
    libId: 'Display:SSD1306',
    name: 'SSD1306',
    description: 'OLED display controller (I2C/SPI)',
    keywords: ['oled', 'display', 'ssd1306', 'i2c'],
    category: 'Misc',
    pinCount: 8,
    defaultValue: 'SSD1306',
    designatorPrefix: 'U',
  },
];

export const CATALOG_CATEGORIES: string[] = [
  'All',
  'Passives',
  'Semiconductors',
  'Amplifiers',
  'Comparators',
  'Regulators',
  'Logic',
  'MCU',
  'Interface',
  'Power',
  'Connectors',
  'Switches',
  'Misc',
];

/**
 * Search the catalog by query string and optional category filter.
 * Returns entries whose name, description, keywords, or libId match all terms.
 */
export function searchCatalog(query: string, category?: string): CatalogEntry[] {
  const terms = query
    .toLowerCase()
    .split(/\s+/)
    .filter((t) => t.length > 0);

  return SYMBOL_CATALOG.filter((entry) => {
    // Category filter (skip if 'All' or undefined)
    if (category && category !== 'All' && entry.category !== category) {
      return false;
    }

    // If no query terms, pass all entries
    if (terms.length === 0) return true;

    const haystack = [
      entry.name,
      entry.description,
      entry.libId,
      entry.category,
      ...entry.keywords,
    ]
      .join(' ')
      .toLowerCase();

    return terms.every((t) => haystack.includes(t));
  });
}
