/**
 * AI prompts used during circuit ingest only.
 * Chat prompts have been removed — AI is upload-summary only.
 */

// ---------------------------------------------------------------------------
// Circuit-summary prompt — runs ONCE per circuit on upload.
// Outputs JSON stored in schematics.ai_summary_struct and used for search.
// ---------------------------------------------------------------------------

export const CIRCUIT_SUMMARY_PROMPT = `You are eencyclopedia's circuit summariser. You will be given a normalised
eencyc-schematic S-expression. Produce a concise, structured summary that
will be used for search indexing and retrieval.

Output JSON only, conforming to this schema:

{
  "topology": "<short label, e.g. 'inverting amplifier', 'low-side N-FET switch', 'CR low-pass filter'>",
  "rails": ["<each named power net, e.g. '+5V', 'GND', 'VBAT'>"],
  "intent": "<one sentence: what this circuit is for / does>",
  "key_components": [
    { "designator": "R1", "mpn": "<if known>", "value": "<if known>", "role": "<short>" }
  ],
  "design_notes": "<2-4 sentences: noteworthy design choices, ratings, things a reviewer would flag>",
  "summary_text": "<150-250 word natural-language summary; this is what gets embedded for search>",
  "concerns": ["<each potential issue: e.g. 'no decoupling on U1', 'R3 dissipates 0.4W in 0603'>"],
  "category": "<analog|digital|power|rf|sensor|interface|protection|mixed>"
}

Rules:
  - Be terse in fields; be thorough in design_notes and concerns.
  - Do not invent MPNs. If a component is shown without an MPN, leave mpn null.
  - Compute roles from connectivity, not labels alone.
  - If the circuit looks broken (floating nets, no GND, etc.), say so in concerns.
`;

// ---------------------------------------------------------------------------
// Datasheet-parse prompt — used by admin ingest for kb_chunks population.
// ---------------------------------------------------------------------------

export const DATASHEET_PARSE_PROMPT = `You will be given the text of a component datasheet. Extract a strict JSON
of structured parameters matching the schema for this component type. If
the datasheet is for a part type we don't recognise, set type="generic".

Output JSON ONLY:
{
  "mpn": "<exact part number>",
  "manufacturer": "<full name>",
  "family": "<product family>",
  "type": "<resistor|capacitor|...|generic>",
  "parameters": { ... },
  "page_refs": { "<param>": <page number> }
}

For each parameter, include the page number in page_refs so we can cite the
datasheet location. Do not invent values. If a parameter is not specified,
omit it. Prefer typ for datasheet "typ" values (Iq, Vos), max for limits (Vmax).
`;

// ---------------------------------------------------------------------------
// Disclosure footer — append to any public-facing AI-generated content.
// ---------------------------------------------------------------------------

export const AI_DISCLOSURE_FOOTER =
  '_Generated by eencyclopedia AI · Verify before use in production._';
